"""
Модуль с фразами для вывода пользователю
"""

TODAY_OUTPUT = "Сегодня"
SUCCESSFULLY_OUTPUT = "✅"
GUARANTEED_ELEMENT = "🆗"
DELETE_OUTPUT = "❌"
CANCEL_OUTPUT = "Выйти в меню📋"
ONLINE_CINEMA_OUTPUT = "онлайн-кинотеатр"
NETWORK_OUTPUT = "сеть-производитель"
STATUS_OUTPUT = "статус"
GENRE_OUTPUT = "жанр"
TYPE_OUTPUT = "тип"
COUNTRY_OUTPUT = "страну"
FINISH_EMOJI_OUTPUT = "🏁"
COMPLETE_SELECTION_OUTPUT = f"ЗАВЕРШИТЬ{FINISH_EMOJI_OUTPUT}"
END_PREVIEW_OUTPUT = f"ЗАВЕРШИТЬ ПРОСМОТР{FINISH_EMOJI_OUTPUT}"
FAVORITE_OUTPUT = "⭐"
HISTORY_OUTPUT = "⌛"
CINEMA_OUTPUT = "🍿"
ACTOR_OUTPUT = "🎭"
DIRECTOR_OUTPUT = "👨‍💼"
SEARCH_OUTPUT = "🔎"
DATE_EXISTS_OUTPUT = "🟢"
REQUIRE_ACTION_OUTPUT = (
    "Выберете действие. Для дополнительной информации о командах нажмите /help"
)
REQUEST_DELETED_OUTPUT = f"Запрос успешно удален{SUCCESSFULLY_OUTPUT}"
